### ISSUE TITLE
handle upload of tag registration recordings

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/motusServer#106]
users upload a .ZIP file with contents:
- one or more .wav files called tagXXX.wav or tag XXX.1.wav (the suffix for repeated IDs with different BI)
- a file called tagreg.txt that looks like this:
```
   motusProjID:  XXX (numeric project ID)
   tagModel: NTQB-??? (as given on the Lotek invoice)
   nomFreq: 166.38 (nominal tag frequency, in MHz)
   species: XXXXX (optional 4-letter code or motus numeric species ID)
   deployDate: YYYY-MM-DD (earliest likely deployment date for any tags)
```
The tags are registered and pushed to motus immediately; users receive an email
confirming and/or informing of any issues.

**Comment by zcrysler** [comment]
These instructions have been incorporated into the tag registration instructions - steps 5-13 at https://sensorgnome.org/VHF_Tag_Registration

**Comment by jbrzusto** [comment]
Thanks - I saw that - looks good.  This issue is just a TODO item that indicates I still need to write code 
to make this happen on the server, which I'm doing this morning.
