### ISSUE TITLE
make receiver summary plots available from realtime status and user upload pages

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/motusServer#137]
We've been linking to the obsolete /SG hierarchy, but now need to establish a new location for the files
we generate upstream of motus.  This includes:
- hourly status plots
- hourly condensed datasets
- processing status

**Comment by StuMackenzie** [comment]
We're not quite ready for review/comment of these status plots yet as Jeremy is still working on them, but when planning for the above it may be useful to keep these in mind and how we might improve the information provided through Motus - https://beta.motus.org/data/receiverTimeline?id=400&year=2015

**Comment by jbrzusto** [comment]
for now:
- serve `/sgm/downloads/projNNN/` using authentication/authorization via mod_authnz_external and a shell script to call the motus user/auth API
- make this available at https://sensorgnome.org/downloads/NNN (for project NNN)
- is that API now returning valid groups?
