### ISSUE TITLE
500 error with authenticate_user

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusServer#237]
https://sgdata.motus.org/data/custom/authenticate_user?json={"password":"secret","user":"sgdata.reader"}

HTTP/1.1 500 Evaluation error [Date: Wed, 30 Aug 2017 19:54:33 GMT, Server: Apache/2.4.10 (Debian), Content-type: text/plain, Connection: close, Transfer-Encoding: chunked]

**Comment by jbrzusto** [comment]
I need to work on the error messages, but this is failing because the data server currently accepts only
POST requests, and the back-end server fails to handle what amounts to missing a missing json parameter gracefully, leading to the 500 error from the front-end proxy server.

**Comment by denislepage** [comment]
I'll check tomorrow, but I am pretty sure I was already using POST. The same request that was working earlier, now giving me 500.

But let me confirm.

Cheers

Denis Lepage
http://avibase.ca
http://ebird.ca


-------- Original message --------

**Comment by denislepage** [comment]
I am indeed using a POST request, but this is now giving me a different error, providing a response this time. The API documentation has the json string in single quotes. I initially tried that, and the only version that worked is what is failing now (without quotes). May not be related.

https://sgdata.motus.org/data/custom/authenticate_user

json={"password":"xxxxx","user":"sgdata.reader"}

{"error":"request is missing a json field or it has invalid JSON"}

**Comment by jbrzusto** [comment]
The query I'm seeing on this end is missing quotes; here's the error
from the log:

Error : lexical error: invalid char in json text.
                                      {authToken":"nbzDC...
                     (right here) ------^
(authToken is missing its opening double quote)

The reason for the single quotes in the API documentation is those
are commands being given in the bash shell.  The single quoting
protects the json payload from being interpreted.

What client are you using to generate the requests?

(I've added better server-side logging of those requests, so can
look again if you retry.)

**Comment by denislepage** [comment]
I’m build a Java client build on the commons apache http package.

funny thing is that the exact same requests were working 1 or 2 days ago, so I am not sure what has changed, but that was probably at the time when you addressed the bug about the + characters being converted.

I just submitted another couple requests on authenticate_user. I haven’t been able to get a token in a couple days.

**Comment by jbrzusto** [comment]
Can you try the authenticate_user call again? I've tried from a couple of different machines using
the userID and password you gave me, and I get an authToken and project list each time.
e.g.
```
curl -s --data-urlencode 'json={"password":"XXX","user":"sgdata.reader"}' https://sgdata.motus.org/data/custom/authenticate_user | bunzip2 -cd
{"authToken":"YYY","expiry":1504467751.1182,"userID":2643,"projects":{"137":"Abiotic and biotic influences on Snowfinch","107":"Acadia National Park","75":"AlaskaBats",...},"receivers":{}}
```

**Comment by denislepage** [comment]
Still the same:

{"error":"request is missing a json field or it has invalid JSON"}

I suspect that something has changed in the handling of the encoding when you fixed your problem.

I may have to encode my JSON differently now. I’ll keep trying a few things.

Denis

**Comment by jbrzusto** [comment]
OK, I've enabled full logging on the apache front-end.  Next time you try I'll have the full
text of the request as it came over the wire.

**Comment by denislepage** [comment]
OK, I’ve tried with both approaches, but same result. First is what I was doing before and working some of the time.

json={"password":"xxxxx","user":"sgdata.reader"}<https://sgdata.motus.org/data/custom/authenticate_user?json=%7b%22password%22:%22xxxxx%22,%22user%22:%22sgdata.reader%22%7d>

This is new (URL encoded json), but same result:

json=%7B%22password%22%3A%xxxxx%22%2C%22user%22%3A%22sgdata.reader%22%7D<https://sgdata.motus.org/data/custom/authenticate_user?json=%7B%22password%22%3A%25xxxxx%22%2C%22user%22%3A%22sgdata.reader%22%7D>

**Comment by jbrzusto** [comment]
You need to be sending the request with Content-Type: application/x-www-form-urlencoded
what I'm seeing in the logs:
```
POST /data/custom/authenticate_user HTTP/1.1\r\n
Content-Type: application/json\r\n
Content-Length: 85\r\n
Host: sgdata.motus.org\r\n
Connection: Keep-Alive\r\n
User-Agent: Apache-HttpClient/4.1.3 (java 1.5)\r\n
\r\n
json=%7B%22password%22%3A%22___%22%2C%22user%22%3A%22sgdata.reader%22%7D
```
where "___" is the password

**Comment by denislepage** [comment]
Partial success!

I am now getting the authToken, but subsequent calls are now failing whenever the + character is part of the token.

https://sgdata.motus.org/data/custom/batches_for_receiver

json={"authToken":"OGa3oimgeA\/zhAOzmVJ6caP+4\/8yvyeMo7uKEJQiJOWE","batchID":0,"deviceID":522}

response:

{"error":"authorization failed"}


json={"authToken":"se\/Ns3doLRmTwBsowdXZK0uEo3YwTB88KLg19wItbo6F","batchID":0,"deviceID":522}

Response:
{"numHits":[19465],"tsStart":[1.4343215778072E9],"motusDeviceID":[522],"motusUserID":["NA"],"motusProjectID":["NA"],"tsEnd":[1.5015153493378E9],"batchID":[17],"motusJobID":[183],"monoBN":[1],"ts":[1.5040112695204E9]}


json={"authToken":"d1b5UeJgpWtvqTDQ7pG47+fqjtyapVPTWtbbPOEBdrqm","batchID":0,"deviceID":522}

response:

{"error":"authorization failed"}

json={"authToken":"Gt5pRV24PDbO3Jyc8nt7zjJojL2K05cW2WBGhI5XKsTf","batchID":0,"deviceID":522}

response:

{"numHits":[19465],"tsStart":[1.4343215778072E9],"motusDeviceID":[522],"motusUserID":["NA"],"motusProjectID":["NA"],"tsEnd":[1.5015153493378E9],"batchID":[17],"motusJobID":[183],"monoBN":[1],"ts":[1.5040112695204E9]}
