### ISSUE TITLE
duplicate ts in gps table

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusServer#241]
The gps query is returning conflicting duplicate keys. It looks like every row is listed twice, unless there is a loss of precision on float values (but 4 decimals means 1/10 of a millisecond, so should be plenty precise).

https://sgdata.motus.org/data/custom/gps_for_receiver?{authToken=xxxx, batchID=8, ts=0.0}

INSERT INTO [sg_gps] ([alt],[lon],[batchID],[lat],[ts]) VALUES (0,0,8,0,1.4298717884511E9)
INSERT INTO [sg_gps] ([alt],[lon],[batchID],[lat],[ts]) VALUES (0,0,8,0,1.4298717884511E9)
INSERT INTO [sg_gps] ([alt],[lon],[batchID],[lat],[ts]) VALUES (0,0,8,0,1.4298753899339E9)
INSERT INTO [sg_gps] ([alt],[lon],[batchID],[lat],[ts]) VALUES (0,0,8,0,1.4298753899339E9)

**Comment by jbrzusto** [comment]
Another query where my elaborate way of authorization via projectID failed to allow for multiple
deployment records of a single receiver.
