### ISSUE TITLE
R tellme and tagme rejecting credentials

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusServer#261]
I tried with 3 accounts, and got 
 The motus data server rejected your login credentials.

Is this a Motus or SG data issue?

Denis

**Comment by denislepage** [comment]
I just checked on the Motus side, and the server seems to be responding with API call https://motus.org/api/user/validate, but the SG api is still not responding. (also note that there is already a return parameter userType in that API call, which is something that was asked for recently).

**Comment by jbrzusto** [comment]
I had turned off reverse-proxying on the front-end Apache server so that I could run a bunch of 
restructuring / indexing queries with locked tables (they wouldn't complete, otherwise).  This was
all to permit substantial optimization of the queries powering `dataServer()`.

**Comment by denislepage** [comment]
Great, I can confirm it is working again.

If there is an opportunity to create an issue before an anticipated outage of the API, that’d be helpful, especially if this anything more than a short while, just so we are aware and can plan a bit around it.

E.g. The SG API will be available tomorrow for a few hours, as I am adding indexes on tables.

Short notice is usually fine (e.g. day before or on the spot), unless it’s a more extended outage. You can then close the issue when the API is available again.
