### ISSUE TITLE
SG status page blank

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusServer#264]
this page appears blank for me: 

https://sgdata.motus.org/status

The /user/validate Motus entry point does return the overall status (e.g. administrator), if you wanted to use that for determining access.

**Comment by jbrzusto** [comment]
1.: server was down briefly.

2.: this is used as of 166fa2de; so far, only the `batches_for_all` API checks it

**Comment by denislepage** [comment]
still blank

**Comment by denislepage** [comment]
still blank. Only for me, however. When I log in as Stu, I can see the status page.

**Comment by jbrzusto** [comment]
I had the wrong user name special cased for you as administrator.  Now it checks for
"dlepage.motus"

This is just the stop-gap; a real status API is coming soon.

**Comment by denislepage** [comment]
thanks!
