### ISSUE TITLE
new SG API query needed

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusServer#265]
I would to create a page on Motus where users can keep track of the processing status of their files along the data flow path.

The current status page (https://sgdata.motus.org/status) is currently showing one record per batchID?

That may be a bit too much to show a complete list of all batches to the users, but we could try to aggregate them meaningfully (ideally by file name originally used in the case of uploads, or something else in the case of automated receivers), so people can verify that 1) the file has been received for processing by sgdata, 2) whether it is currently being processed by sgdata, 3) whether it is pending transfer into the motus database, or 4) whether the whole process is completed.

The image is just a wish list of what I would like to see. We can generate much of these summaries from the Motus data at the moment. Except 1) we don't have the file name or something to a label that people can recognize linking to the upload event and 2) we don't have a way of generating this until the data is fully transferred. Some of the summaries (number of batches, date range and number of hits) could be done only from the Motus database, but the rest would be useful to have from the SG API as soon as the file gets queued.

![image](https://user-images.githubusercontent.com/21110542/30617298-630df794-9d63-11e7-90d7-fce51cd4e6dd.png)

That would entail creating a distinct entry point similar to batches_for_receivers but which 1) exposes all batches, regardless of the status and 2 provides a few additional fields such as file name, identity of uploader, date uploaded, processing status, etc.

That would allow users to troubleshoot themselves of lot of potential issues regarding missing data, by first confirming that the data actually was received and processed.

I think this would be a relatively high priority on the wish list, if possible.

**Comment by jbrzusto** [comment]
closing in deference to #222
