### ISSUE TITLE
new API options 

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusServer#266]
1) It'd be great to have a way to get all batches across all receivers when using batches_for_receiver. IE, create an identical API entry, but remove the requirement to provide a receiver ID.

When transferring the data into Motus, I currently have to loop through all receivers. I'd like to just be able to say: give me to next batch ID's across all receivers, starting at batch XXX.

By the way, I am presuming that batches that fail to process get reassigned new batchID numbers, so I can always assume that I have all the data up to the last batchID I got?

This call would presumably only be available to specific users with full access (I create a single account for the transfer which we can hard-code, or add a special permission that we return in the Motus authentication API for that strict purpose).

2) Also, for all API calls, adding a parameter controlling the page size (number of records returned) would help minimize the number of connections I need to make to the API. Right now, the number of records is undocumented, so I always have to make a final call that returns 0 records to know that paging is done. If I knew exactly how many records were expected (which would be easier to know if I can make it part of my API call), then I would know that any response containing less than my page size is the last one.

**Comment by jbrzusto** [comment]
for now:
- I'm not sure minimizing the number of connections is important; I don't really want to give clients
  the ability to tie-up the single-threaded server in a long query, leaving any other users with 
  queries that time out.

 - a query to count available data items is often almost as expensive as the queries to actually fetch    them, so figuring out how many rows are available in advance doesn't seem worth the trouble
   (although, see the size_of_* API calls)

- all queries by dataServer() are implemented independently.  This avoids all the overhead of
  session management and so on.  However, it does mean that the dataServer doesn't know that
  it's the "end of data" until it tries to satisfy your last paging request.  However, for now, the
  maximum number of rows returned by any of the queries is 10000, so if you get fewer than that,
  you can skip the next call.  I didn't bother doing that in the reference client implementation
  in the `jbrzusto/motus::motusUpdateXXX()` functions

All of which reminds me that I need to add a max. batchID item on a bunch of the queries (i.e. #269)

**Comment by jbrzusto** [comment]
2. is now addressed by:  83117dea19d18cb81abc8e5aae3fe480883129ed and bfc72bbff63db6b3675a03c8f117c527ae0353b7

**Comment by denislepage** [comment]
For #1 above.

This function, which is a slight modification on batches_for_receivers, should give me what I need to pull in all data into the Motus database irrespective of projects and avoid calling ~1000 receivers when checking if there is any new data. I noticed that you are subsetting all receiver calls (runs, gps and hits) by the list of projects authorized for a given user, which I would expect. Given that the sgdata.reader user will have full access, this should give me all data. The only thing to watch is if you create a new project, the cache of permissions on SG data should also be updated, so the new project remains visible to this user.

An alternative is to create new function calls (runs_full, hits_full and gps_full) that are limited to the sgdata.reader user and do not filter by project permissions (permissions would be validated at the top of the function), but I can otherwise use the existing receiver calls with the batchID's generated by this function below.

In dataServer.R, add new function:

#' get batches across entire database
#'
#' @param batchID integer batchID; only batches with larger batchID are returned
#'
#' @return a data frame with the same schema as the batches table, but JSON-encoded as a list of columns

batches_full = function(env) {

    json = fromJSON(parent.frame()$postBody["json"])
    res = Rook::Response$new()

    if (tracing)
        browser()

    #TODO: validate to ensure that this call is only made by user sgdata.reader. We can also add a special type of permission in the motus database that could apply to multiple users.

    auth = validate_request(json, res, needProjectID=FALSE)
    if (is.null(auth))
        return(res$finish())

    sendHeader(res)

    batchID = (json$batchID %>% as.integer)[1]
    if (!isTRUE(is.finite(batchID)))
        batchID = 0

    ## select batches

    query = sprintf("
select
   t1.batchID,
   t1.motusDeviceID,
   t1.monoBN,
   t1.tsStart,
   t1.tsEnd,
   t1.numHits,
   t1.ts,
   t1.motusUserID,
   t1.motusProjectID,
   t1.motusJobID
from
   batches as t1
where
   t1.batchID > %d
order by
   t1.batchID
limit %d
",
batchID, MAX_ROWS_PER_REQUEST)
    rv = MotusDB(query)
    res$body = makeBody(rv)
    res$finish()
}
