### ISSUE TITLE
ant field returned by `runs_for_*` API entries contain strange values

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/motusServer#272]
From @denislepage

> What does the ant = -48 represent?
>
> select * from runs where ant = -48
>

and

> 3. are the ant = -1 read the same way? Presumably.

**Comment by jbrzusto** [comment]
Weird, I hadn't noticed `ant=-48` before - will investigate; surely a bug.

`ant = -1` represents the Lotek composite antenna `A1+A2+A3+A4`.  I don't
know what that actually means; i.e. whether the atenna signals are
somehow added in analog or digital form, and pulses detected from the
fused signal, or whether it's a detection of a burst without regard for
which antenna(s) the pulses within the burst come from.  But .DTA files
sometimes report that as the antenna on which a tag was detected.

I was reluctant to use character strings to represent antennas, as in
almost all cases, a small integer suffices, so used -1 for this case.
Normally, ant is a positive integer, where the receiver has the
capacity for more than one antenna (e.g. via a USB hub for SGs, or an
antenna switcher for Lotek receivers).  But it's 0 when there's no hub
or antenna switcher, and the only antenna is attached directly to the
receiver.

**Comment by jbrzusto** [comment]
"-48" is what "A0" is being translated to from the Lotek .DTA files.  That code is only present in a limited
number of .DTA files, and only three receivers had any tag runs with that antenna code:
Lotek-279, Lotek-280, Lotek-384

I don't know how "A0" compares to "AH0" in meaning, because the latter is much more common in
.DTA files, and apparently means *antenna connected directly to receiver*.

For now, I'm tempted to just leave this as-is, and just note that ant=-48 means *A0* was the antenna
in the .DTA file; alternatively, we can refile this as an issue against jbrzusto/find_tags to the effect
that *A0* should be recorded as a negative integer of smaller magnitude.

**Comment by denislepage** [comment]
Sounds ok to leave as is for now.

This is not something we need to capture in the metadata in any case. There may be a few places where we will have to handle them specifically, especially on the output side.
