### ISSUE TITLE
false detections for tagID 20802

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusServer#280]
This deployment 8617 (tagID 20802) is one example with problems that we are trying to understand.

https://motus.org/data/track?tagDeploymentId=8617

This is a Black-backed Woodpecker relseased in Québec and should be nowhere near some of the places where it is being reported. 

latitude	longitude
47.40000000	-71.09000000

There doesn't seem to be other tags with the same properties (the closest is a Whimbrel with the same codeset, but a different period (6.1 vs. 5.9 for BBWO), so that it likely not a case of ambiguities, but rather false positives.

When I looked at the detection and runs data, I made a summary of the runs of length 2, to confirm the duration between pulses. the min(ts) and max(ts) match the expected values from the runs table (tsStart and tsSend), but the difference between the 2 hits within the same runs goes from anywhere between 5.9 (the expected value) and 82 seconds. There are only 5 runs with the correct burst interval of 5.9. I imagine the others are multiples of the period, with some margin of error. 

select ISNULL(a.motusTagID, c.motusTagID) as motusTagID, c.runID, c.tsBegin, c.tsEnd, c.tsEnd - c.tsBegin, d.period, (c.tsEnd - c.tsBegin) / period
 from sg_runs c left join sg_ambig_tags a on c.ambigID = a.ambigID
 inner join tags d on ISNULL(a.motusTagID, c.motusTagID) = d.id
 where isnull(a.motusTagID, c.motusTagID) = 20802
 and len = 2

In the case of this tag, the period of a run length 2 can be as high as 14 times the tag period. In some cases however (for other tags), the gap between the 2 detections is as high as 60 times the period of the tag. 

This is potentially contributing to many of the false positives? In the case of the tag 20802, there are many runs where the interval between the 2 hits are more than 10 times the period.

It seems like there should be an upper limit to the minimum detection interval within a run (e.g. a run should have at least 2 consecutive bursts no more than 5 or 10 times the tag period). What is the limit now? Having that value  inserted in the runs table  (the minimum interval between 2 consecutive hits within a run) would also allow us to create filters that allow users to be more or less lenient on that topic.

Can it be added to the runs table? It could be calculated from the data, but that would be presumably more efficient to do during processing?

**Comment by jbrzusto** [comment]
please see the discussion here:

https://github.com/jbrzusto/motusServer/blob/new_server/inst/doc/tag_detection_imprecision.md

Also, the parameters (and version) used in every run of the tag finder are recorded on the server.  If it's useful, I can add API entries to provide this downstream.

**Comment by denislepage** [comment]
As we discussed on Monday’s call, many of the issues were related to run lengths of 2, which were included.

Restricting to longer run lengths do not remove all problems, but a vast majority of them, so this may be sufficient for now.

Having a list of the parameters generated by the tag finder may be useful at some point, at least to decide whether they can be incorporated within the model.

If you could provide me instructions for how I can access the database in Linux, I can have a look at the information there directly. That would be useful for me to have, as discussed earlier.

Denis
