### ISSUE TITLE
XXX_for_receiver API entries return nothing for batches where recvDepProjectID is null

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/motusServer#282]
(Reported by @denislepage)

> The following call returns empty, but should have data.
>
> https://sgdata.motus.org/data/custom/hits_for_receiver
>
> {hitID=0, authToken=xxxx, batchID=19798}
>
>
> {"hitID":[],"runID":[],"batchID":[],"ts":[],"sig":[],"sigSD":[],"noise":[],"freq":[],"freqSD":[],"slop":[],"burstSlop":[]}
>
> I see that the motusServer's call filters on recDepDeployID, but I think this is one of those cases where there are no deployments available for some of the hits (this is actually exactly what I was trying to investigate, so it's not a coincidence that I am hitting those records).
>
> I am also getting an empty response for runs for the same batchID.
>
> This is problematic and probably explains why I am missing these records.

**Comment by jbrzusto** [comment]
I forgot some batches might not be covered by a current receiver deployment record, so would
have `null` for  `recvDepProjectID`.  
I'll set `recvDepProjectID = -1`  for those batches, then include `-1` in the project list for admin users.

**Comment by jbrzusto** [comment]
The fix seems to have worked, as seen in this R session (from after
restarting the dataServer with the fix):

```R
> library(motusClient)
> a=srvHitsForReceiver(batchID=19798)
Please enter a value for login name at motus.org
==> john
Please enter a value for password at motus.org
==> ...
> a=srvHitsForReceiver(batchID=19798)
> dim(a)
[1] 10000    11
> names(a)
 [1] "hitID"     "runID"     "batchID"   "ts"        "sig"       "sigSD"
 [7] "noise"     "freq"      "freqSD"    "slop"      "burstSlop"
> unique(a$batchID)
[1] 19798
> b=srvRunsForReceiver(batchID=19798)
> dim(b)
[1] 1399    8
> a2=srvHitsForReceiver(batchID=19798, hitID=max(a$hitID))
> a3=srvHitsForReceiver(batchID=19798, hitID=max(a2$hitID))
> a4=srvHitsForReceiver(batchID=19798, hitID=max(a3$hitID))
> dim(a4)
[1] 52 11
> g=srvGPSforReceiver(batchID=19798)
> dim(g)
[1] 1105    6
> p = srvPulseCountsforReceiver(batchID=19798, ant=0)
> dim(p)
[1] 3021    4
> srvSizeOfUpdateForReceiver(148, 19797) - srvSizeOfUpdateForReceiver(148, 19798)
  numBatches numRuns numHits numGPS numBytes
1          1    1399   30052   1105  3152286

```
i.e. 1399 runs and 10000+10000+10000+52 = 30052 hits, 1105 GPS records,
and 3021 pulse counts, which match these queries directly on the master DB:
```SQL

MariaDB [motus]> select count(*) from runs where batchIDbegin=19798;
+----------+
| count(*) |
+----------+
|     1399 |
+----------+
MariaDB [motus]> select count(*) from hits where batchID=19798;
+----------+
| count(*) |
+----------+
|    30052 |
+----------+
MariaDB [motus]> select count(*) from gps where batchID=19798;
+----------+
| count(*) |
+----------+
|     1105 |
+----------+
MariaDB [motus]> select count(*) from pulseCounts where batchID=19798;
+----------+
| count(*) |
+----------+
|     3021 |
+----------+
```

**Comment by denislepage** [comment]
Yup, seems to work now!

Thanks
