### ISSUE TITLE
runs_for_receiver batchID = 102762, runID = 18368459

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusServer#283]
I expected the runs_for_receiver for receiver API call to only give me runs that started on a specific batch (batchIDBegin). This concept has worked for all batches, except this one:

Request:
{authToken=xxxx, runID=0, batchID=**102762**}

Response:
{"batchIDbegin":[**83755**],"len":[23],"ant":[1],"motusTagID":[23054],"runID":[18368459],"tsBegin":[1.487808084508E9],"tsEnd":[1.4878083067913E9],"done":[0]}

I can confirm in the SG database that this is the only occurrence where the batchID in batchRuns doesn't match the batchIDBegin in runs.

select t1.* from runs t1 inner join batchRuns t2 on t1.runID = t2.runID join batches t3 on t3.batchID = t2.batchID where t2.batchID != batchIDbegin limit 10;

This is currently preventing the import of that batch, because the runs is getting imported again. I can easily deal with this case, but it would be good to understand how this happened.

**Comment by jbrzusto** [comment]
This will happen much more often than indicated by that query.   Runs are not generally nested within batches, although the full rerun of the receivers currently on the new server might suggest that.  Batches arise from arbitrary divisions in the continuous stream of data produced by
a receiver in these ways:
- data downloaded from a site visit to an isolated receiver
- data synced (~ hourly) from a networked receiver
- data re-run from an archive, where batches have been arbitrarily equated to boot sessions.

Most (all but the one above?) of the batches currently on the new server arose in the last way, but that will change as new data are moved from the old server, and as receiver networking switches from the old to the new server.

So in general, a run starts in one batch, might last through several subsequent batches, and then
end in a final batch.  A run ends when detections of that tag have become "stale" enough,
according to the tag's burst interval, and parameters to the tag finder (`max_skipped_bursts`).

The `batchParams` table records which runs are *active* in which batches, where a run is active if it
either has detections in a batch or persists throughout that batch into a later one (that would
be rare, but possible in the case of a batch covering a very short time period).

So although I'm surprised there's only one such situation in the current database on the new server,
there will be many more soon.

The `runs_for_*` API entries provide `runs` records for each batch where the run is active, and in
the case of batches *after* the one the run starts in, the information in those records is the new
(cumulative) length and ending timestamp **so far**.

The functions `motusUpdateTagDB` and `motusUpdateRecvDB` call `dbInsertOrReplace` with the runs records they receive from the corresponding API entries.  This serves to both add new run records, and update any existing ones which are still active in the new batch.

**Comment by denislepage** [comment]
But shouldn’t I be getting the run records only on the starting batch?

Right now, the run 18368459 is being pulled for both instances when I asked for runs_for_receiver for batchID 102762 and 83755 from the api (runs_for_receiver).

What is the purpose of providing the same run records on multiple calls with different batchID?

I thought the runs were only being provided when the batchID matched the batchIDBegin, but the query in motusServer relies rather on the batchID from batchRuns, which in this case (only) doesn’t match batchIDBegin.

We may need to go through the logic of how I should be coming in to get the entire database. Right now, this is the only case where I’ve run into a conflict of a record being imported twice and breaking the primary key rules, so it’s a bit of a puzzle for now.

**Comment by jbrzusto** [comment]
I think maybe the behaviour seems weird because you're polling after *both* batches already exist.
That's not going to be typical going forward, when new batches will be added all the time, and
there will be plenty of runs crossing batch boundaries.
So in this example, what if you had called the API before the second batch was created?  Then when the
second batch was processed on the data server, the run record there would be updated,
and if you polled again after that, the run would be returned in the API call for the second batch,
but with updated `len`, and `tsEnd`, and `done` fields.

I haven't documented the full logic of updating outside of the code and comments in the two `motusUpdateXXXDB` functions mentioned above.

**Comment by denislepage** [comment]
I am not sure I follow.

If the run is starting in batch #1, I would expect the run record to be only returned by the api associated with batchID #1.

If the run continues at any point on another batch, I would not expect the batchIDBegin to ever change, nor to need to be returned by the API after the initial batch.

In your example, I would not expect the run to be returned in the second batch. Only hits and gps.

In other word, I think the batchIDBegin in the response matches the batchID of the request in all cases, which I would expect, but except this case.


-------- Original message --------

**Comment by jbrzusto** [comment]
`batchIDbegin` is the ID of the batch in which the run starts, and never changes. But the `len`, `done`, and
`tsEnd` fields can change in this scenario:

time|event|comments
---|---|---
1|1st batch of data from receiver R processed|tag T is detected 5 times
2|API call: runs_for_receiver(batchID=1)|returns run {runID:1, batchIDbegin:1, motusTagID:T, length:5, tsBegin:1.1, tsEnd:1.9, done:0}
3|2nd batch of data from receiver R processed|tag T is detected 5 times; batch2 immediately follows batch1 in time; run of T ends
4|API call: runs_for_receiver(batchID=2)|returns run {runID:1, batchIDbegin:1, motusTagID:T, length:10, tsBegin:1.1, tsEnd:2.3, done:1}

The documentation isn't clear on this.  It says the API calls returns

>   runs from batch `batchID`

but should say that it returns

 >  runs begun, extended, or ended in batch `batchID`

I've fixed the docs.
