### ISSUE TITLE
batches where transfer to master DB failed should be excluded from dataServer replies

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/motusServer#286]
Such failures are presumably due to bugs.  The partial batches should be removed from the master DB,
but in the meantime, we don't want the dataServer providing them to end users.

e.g. batches 102755 to 102769 (except 102763).

Records for such incomplete batches have `tsMotus = -1`.

**Comment by cjardine-bsc** [comment]
There are no batches in the master DB with tsMotus = -1. 

The batches you mention above do exist in the DB with valid tsMotus. See below sheet. 

[batches.xlsx](https://github.com/jbrzusto/motusServer/files/1511052/batches.xlsx)

**Comment by jbrzusto** [comment]
I mean the master DB on sgdata.motus.org; see the table in #285.
I don't have access to any other master DB...
