### ISSUE TITLE
batches for tag project

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusServer#302]
I am trying to update the static sqlite files on the motus server with the newest data, but it doesn't seem to work as expected.

The highest batchID that this gives me is 101692, but there should be numerous batches up to 113738. I tried both using an admin user to read the data, and one that has specific permission on project 35. I can also confirm that the authentication key returned includes project 35 in both cases.

https://sgdata.motus.org/data/custom/batches_for_tag_project
{authToken=xxx, batchID=0, projectID=35}

I just realized that the result seem to be to same (222 batches), regardless of the projectID used, even for those what have no runs or tags registered.

https://sgdata.motus.org/data/custom/batches_for_tag_project
{authToken=xxx, batchID=0, projectID=179}

batchID=[187,262,305,313,315,324,353,354,356,357,359,360,361,362,376,396,421,424,431,441,443,444,463,464,478,562,575,578,579,580,581,582,706,724,731,783,787,788,792,803,806,809,811,812,820,821,822,826,827,828,830,831,832,838,844,845,847,848,849,850,851,854,855,856,857,858,859,860,861,862,863,865,869,875,876,886,887,888,889,890,891,892,893,894,895,896,901,902,903,906,913,914,923,924,925,929,930,935,952,953,954,955,956,957,958,1093,1095,1097,1098,1099,1101,1103,1104,1106,1107,1108,1109,1953,3682,3700,3705,4451,4452,4595,4601,4608,4610,4611,4628,4629,4630,4631,4649,4664,4687,4694,4697,4889,5031,5032,5052,5060,5069,5347,5586,5589,5590,5592,5593,5594,5595,5632,5668,6095,16965,18784,28038,28047,28049,34216,34337,37336,37340,37341,38366,40310,45528,46296,47960,49866,50434,52940,53908,54461,54872,55325,56966,60531,64410,64426,64436,64481,64491,65536,65874,65889,66141,66146,66190,66251,66648,67093,67429,68155,68156,68892,72014,73362,73370,74503,74504,74747,74790,76847,79520,79522,79523,79524,79525,79527,79620,79635,87282,92795,99364,99513,101692]

**Comment by denislepage** [comment]
I think I have found the problem:

in batches_for_tag_project, the query string has 4 replacement parameters, but I think they are out of order.

    query = sprintf("
select
   t1.batchID,
   t1.motusDeviceID,
   t1.monoBN,
   t1.tsStart,
   t1.tsEnd,
   t1.numHits,
   t1.ts,
   t1.motusUserID,
   t1.motusProjectID,
   t1.motusJobID
from
   projBatch as t2
   join batches as t1
   on t2.tagDepProjectID=%d
   and t2.batchID > %d
   and t1.batchID = t2.batchID
   and t1.status >= %d
order by
   t2.batchID
limit %d
",
minBatchStatus, auth$projectID, batchID, MAX_ROWS_PER_REQUEST)
    return_from_app(MotusDB(query))
}


Should become(?)

**auth$projectID, batchID, minBatchStatus, MAX_ROWS_PER_REQUEST**

**Comment by jbrzusto** [comment]
Ouch - good catch!  I  will check in a fix this evening.
