### ISSUE TITLE
batchID 68902

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusServer#303]
BatchID 68902 has over 6 million runs, from 150 different tags over about 2 months. That represents an average of 666 runs per tag per day, roughly, but they are not spread evenly.

Among those, the tag with the most runs, tagID 16365, has 813,578 runs over 2 months or 1 run, on average, every 6 seconds (burst interval is 2.3 seconds). This is a piping plover, presumably at all times within the range of the receiver (from early July to late August), but even so, the number of runs seems very high. The number of hits is roughly twice as high as the number of runs (1,655,992), suggesting that almost all runs have only 2 detections.

This run has been causing us query timeout problems, which we can try to optimize, but I am unclear if having as many runs is the result of a bug in tag finder. This doesn't seem to happen at the same scale for any/many other batches (the next biggest batch is 1.4 million runs), so I am not sure what is particular about this one.

**Comment by jbrzusto** [comment]
Almost entirely (~99.5%) bogus hits and runs from a receiver with an extremely bad noise / signal processing bug situation:

```sql
MariaDB [motus]> select * from batches where batchID=68902;
+---------+---------------+--------+----------------+-----------------+----------+-----------------+-------------+----------------+------------+------------------+--------+
| batchID | motusDeviceID | monoBN | tsStart        | tsEnd           | numHits  | ts              | motusUserID | motusProjectID | motusJobID | recvDepProjectID | status |
+---------+---------------+--------+----------------+-----------------+----------+-----------------+-------------+----------------+------------+------------------+--------+
|   68902 |           315 |    236 | 1435839973.967 | 1440660312.6412 | 14420377 | 1505144433.7225 |        NULL |           NULL |      64162 |                1 |      1 |
+---------+---------------+--------+----------------+-----------------+----------+-----------------+-------------+----------------+------------+------------------+--------+
MariaDB [motus]> select count(*) from runs where batchIDbegin=68902 and len=2;
+----------+
| count(*) |
+----------+
|  6316873 |
+----------+
1 row in set (1 min 20.81 sec)

MariaDB [motus]> select count(*) from runs where batchIDbegin=68902 and len=3;
select count(*) from runs where batchIDbegin=68902 and len>3;
+----------+
| count(*) |
+----------+
|   488346 |
+----------+
MariaDB [motus]> select count(*) from runs where batchIDbegin=68902 and len=4;
+----------+
| count(*) |
+----------+
|    60962 |
+----------+
MariaDB [motus]> select count(*) from runs where batchIDbegin=68902 and len>4;
+----------+
| count(*) |
+----------+
|    14612 |
+----------+

```
The rapid drop in counts of run by length is typical for such sites.

Except for unusually quiet sites, a run of length 2 shouldn't be considered real data.
For extremely noisy sites, such as this one, even length 3 or 4 isn't likely enough.

**Comment by denislepage** [comment]
If you look at consecutive runs of the same tag, the majority have runs that start before the previous one is terminated, which we know can’t happen.

IE, runs are overlapping in time for the same tag. Of the first 10,000 runs for tag 16365 in that batch, 9400 have tsBegin that is earlier than the tsEnd of the batch that started previously. E.g.

runID

batchIDbegin

tsBegin

tsEnd

10751021

68902

1435840524

1435840542

10751016

68902

1435840526

1435840538


The same way, the delay between the end of a run and the start of a new one should be a multiple of the bi (in which case they’d be treated as part of the same run, I assume).

Of course, there is no easy way to deal with this rule. Even if we know it’s wrong to have overlapping runs, I’m not sure how we determine that some are valid and not others, other than we know for a fact that not all of them can be valid. In a case like this, as you point out, I am not even sure I would trust run lengths > 2, especially for tags that have lots of runLen = 2.

I am nonetheless wondering if these rules could be used as part of our filtering process to identify bad runs post-processing. IE, if I take the interval between all consecutive detections in a batch for a single tag, I would expect all intervals to be a multiple of the tag BI. In a case like this, the intervals would be all over the place, and I would probably make the decision to exclude the entire tag from the batch.

Something for us to consider. I don’t know if any of that information is available from the tag finder (e.g. interval from previous detections within or across runs for a given tag).

**Comment by jbrzusto** [comment]
The tag finder is the place to do this filtering.  Its parameters can be overridden to accomodate unusually noisy or quiet sites.  Some, such as this one, will obviously need to be re-run with much more stringent filtering.  There's a database table of parameter overrides that is consulted before each tag finder run,
to see whether there are any non-default parameter values that should be used with the given receiver
and boot session.

And interleaved runs are not necessarily incorrect; if there are two ambiguous tags that happen to 
be in the same area, then their runs will be interleaved.  But that's a low probability event.

The best approach to this problem would be to introduce a probabilistic model at the tag-finder level,
to assign a P-value to each run of detections.

**Comment by denislepage** [comment]
I am closing this issue for the time being. We're looking into identifying some of the noisy runs after the processing in the Motus database. There's a balance to reach between how much raw data we provide to users and how much we try to pre-filter them. Tightening the rules within the tag finder will like remove valid data as well, and I think we need to do more work to decide how to correctly separate bad from good data. That will take a bit of time. At this point, I don't think we should consider any significant changes to the tag finder processing, other than address obvious bugs.
