### ISSUE TITLE
status API:  support returning count of jobs with at least one subjob error

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/motusServer#330]
@pmorrill writes:
```
Subject: Status API
Date:    Thursday, January 25, 2018 16:24

Hi John

I wonder: would it be difficult to adjust the /list_jobs handler
slightly, so that I could use the 'countOnly' option while also
specifying the 'errorOnly' option? I'd like to be able to report a
count on jobs with errors on our web page.
...

```

**Comment by pmorrill** [comment]
John: when I submit the following to /list_jobs, I get back a count of 113

 {"authToken":"wCsiL3iGDZ5Iuai5SSJ6Y40qY2fyR3FLTeFnTeD3zzy0","options":{"countOnly":true,},"projectID":1}

But when I submit the following, I get back a count of 445. Given that the 113 includes error records, something might be amiss.

 {"authToken":"wCsiL3iGDZ5Iuai5SSJ6Y40qY2fyR3FLTeFnTeD3zzy0","options":{"countOnly":true,"errorOnly":true},"projectID":1}

**Comment by jbrzusto** [comment]
The problem is `motusServer::list_jobs()` is ignoring `projectID` if both `errorOnly` and `countOnly` are `true`.  I had special-cased that combination of options, bypassing selection by other criteria.  
I'll insert the selection criteria into that query.

**Comment by pmorrill** [comment]
it's suddenly working, yes. Thank-you
