### ISSUE TITLE
Limit Option may not be working

### ISSUE THREAD

**Issue by pmorrill** [jbrzusto/motusServer#343]
John: when I submit the below query to /list_jobs, I am still receiving 20 records in the response:

 {"authToken":"xxxxxxxxxxxxxx,"options":{"limit":10},"projectID":1}

Am I misunderstanding the limit parameter?

**Comment by jbrzusto** [comment]
Oops - code / doc mismatch:  `options.limit` was being fetched from `select.maxRows`.

**Comment by jbrzusto** [comment]
also, see 95dc365627eeccda3b1b41c5ed835a71f3adfd98 for notes on `options.limit`
