### ISSUE TITLE
move .sqlite DBs back to main disk from NFS

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/motusServer#346]
e.g. server.sqlite and all receiver DBs.

see [here](https://stackoverflow.com/questions/9907429/locking-sqlite-file-on-nfs-filesystem-possible#9962003) for one opinion in favour of this.

Also, things like loading the page at https://sgdata.motus.org/status often seems oddly slow, even with
no load on the server.  Unlike mariadb where all requests to backing storage go through a single
process that can cache and buffer, each process using `server.sqlite` is working directly with pages 
of that file from disk.

**Comment by denislepage** [comment]
If you move the files back to the server, you would still ideally use the shared drive for backup, assuming you can set it up that way as a nightly job?

Kwic may also be mirroring the whole server, but I can’t remember what we concluded on that?

**Comment by jbrzusto** [comment]
- [ ] move server.sqlite, receivers.sqlite, ... - all smaller .sqlite DBs to which we need frequent, low-latency
access for small queries from multiple processes
- [ ] don't move receiver DBs (too big; access is typically for longer periods, protected by a lock)
- [ ] reinstate nightly backups of these DBs to NAS
