### ISSUE TITLE
status API:  add ability to get, set, and delete rules for assigning files to duplicate receivers

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/motusServer#363]
- currently works as a hard-coded table in `parseFileNames()`
- should instead come from a database table which the API accesses:

```sql
CREATE TABLE serno_collision_fixes (
    id INTEGER PRIMARY KEY NOT NULL,  -- unique ID for manipulation by API
    serno CHAR(16) NOT NULL,          -- receiver serial number (which
                                      -- is shared by 2 or more receivers)
    cond VARCHAR NOT NULL,            -- R expression involving
                                      -- components of the filename.  For SG receivers:
                                      --   prefix: short site code set on receiver
                                      --   bootnum: integer (uncorrected) boot count
                                      --   ts: timestamp of file as YYYY-MM-DDTHH-MM-SS.SSSS
                                      --   extension: usually `txt`
                                      --   comp: usually `gz`
                                      -- For Lotek receivers, the only component is `site_code`, an integer from 0...9999
                                      -- when TRUE, this rule applies
    suffix VARCHAR NOT NULL           -- suffix this rule appends to serno
                                      -- when `cond` is true
);
```
Current rules are:
```SQL
( 1,  'SG-1614BBBK1911',  'prefix != "Lepreau"', '_1'),
( 2,  'SG-0517BBBK1111',  'prefix != "Bookton"', '_1'),
```

**Comment by jbrzusto** [comment]
We need another rule for duplicated Lotek-270, HOFT/winous point, projects 32/64 respectively
For Lotek receivers, we need to add fields parsed from the .DTA file to the variables available for
the rule.

**Comment by denislepage** [comment]
It might be useful to add a field in the Motus database for receivers that maintains the original receiver serial for each, in addition to the resolved ID that deals with conflicts? That could be the raw serial number value read from the receivers also, without any assumption that they need to be unique.

If the resolution rule is always straightforward, we may not need it, but I’m offering it as an option, which would potentially avoid having to resolve back the original serial when needed.

**Comment by jbrzusto** [comment]
### Implementation: ###
- [ ] add `serno_collision_rules` table to metadata schema
- [ ] change `parseFilenames()` to resolve serial number collisions using the new DB (for SGs)
- [ ] change `readDTA()` to read the `Site Code:` field 
- [ ] change `readDTA()` to resolve serial number collisions using the new DB (for Lotek receivers)
- [ ] populate the table with the existing collision rules
- [ ] document the new status API entries for serial number collisions
- [ ] implement the new status API entries for serial number collisions
