### ISSUE TITLE
handleRegisterTags() failing to lookup species code

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/motusServer#369]
e.g. [job  139884](https://sgdata.motus.org/status?jobID=139884)

where code is "YRWA"

**Comment by denislepage** [comment]
That may have been with my tests, but I also noticed it failed to recognize the species in my trials.

In the tag recording instructions on sensorgnome, the example is PTWA, but our code for this species is PROW. Are you entirely basing you lookup in Motus species API? Just curious.

YRWA should be the same in any scheme, anyway.
