### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Hussell** [jbrzusto/motusServer#371]
I'm attempting to install motusServer on a fresh Ubuntu desktop for testing. Issues I've encountered so far:
- ensureServerDirs fails to create /sgm/uploads/partial (I'm unsure why)
- ensureServerDB calls lockSymbol before ensuring that MOTUS_SYMBOLIC_LOCK_TABLE exists
- openMotusDB (which initializes the MotusDB global variable) checks for the existence of MotusDB using the table bumpCounter, which is created by ensureMotusTransferTables, which in turn requires MotusDB already be initialized

**Comment by jbrzusto** [comment]
Thanks!  There are probably a number of such dependency cycles that I've failed to catch because
I'm always re-installing the package in the context of an already-existing server.

**Comment by jbrzusto** [comment]
Would you mind filing such issues individually from now on?  (I'll deal with these as filed, but it's easier to 
work with them one at a time, especially when the underlying causes might be quite different.)

**Comment by jbrzusto** [comment]
The problem with ensureServerDIrs might be that the linux user you are installing / running the package
with lacks password-less sudo capability.  Does it report any error?

**Comment by Hussell** [comment]
The complete error message I get is:
```
Error in safeSys("chmod", a$perm, MOTUS_PATH[[i]]) :
 Error 1 from 'chmod' 'g+rws' '/sgm/uploads/partial'':
chmod: cannot access '/sgm/uploads/partial': No such file or directory
```

At this point /sgm/uploads has been created, but /sgm/uploads/partial has not.
