### ISSUE TITLE
tag registration fails when user-specified start date is in future

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/motusServer#382]
e.g.

   https://sgdata.motus.org/status?jobID=159546

Apparently `tsAnticipated` is no longer used by the Motus tag/register API, and we should just use `tsStart`
regardless of whether the date is in the past or future.

**Comment by pmorrill** [comment]
We no longer use the tsAnticipated field. If a tag deployment start date is in the future, we accept it, but set a flag on the record specifying that the start date is unconfirmed. This flag is really only used to prompt the user to confirm the start date later, once it has passed. (We have a notification / status page that displays warnings and suggestions).

The end result is that start date is mandatory, and can be in the future.

**Comment by jbrzusto** [comment]
Okay, I've fixed that on my side, but it's not working on yours: MotusDev/MotusAPI#5

**Comment by pmorrill** [comment]
I will check that!
