### ISSUE TITLE
Jobs failing with "Error in dir(dst): 'translateCharUTF8' must be called on a CHARSXP"

### ISSUE THREAD

**Issue by Hussell** [jbrzusto/motusServer#398]
This seems to happen when dst = "/sgm/trash". From Googling, it looks like this isn't actually anything to do with UTF8, locale, or character sets. Instead, it looks like it's an issue with R memory corruption, possibly due to a large number of files being in "/sgm/trash". I say "possibly" because running ls on that directory hangs for me, so I don't actually have any idea how many files are in that directory.

Edit: ls going through now, though still very slow. Lists ~397,640 files in /sgm/trash.

**Comment by Hussell** [comment]
I propose to delete all files in /sgm/trash/ which are 90 days or older using the following command:
find /sgm/trash/ -mindepth 1 -mtime +90 -delete

Testing this command with -delete replaced by -depth -print returned a list of 1,675,717 files (more than ls because I didn't use -R to get recursive listing of subdirectories). Testing to find a list of files less than 90 days old returned a list of 193,283 files.

**Comment by Hussell** [comment]
I moved all files 30 days or older to another directory, and this initially seemed to work: I retried all previous jobs which had this error and they all went through (though a few didn't complete, instead generating new errors). But now some new jobs have generated this error, and retrying them isn't working.

I suspected that there was memory corruption in R, and my restart of the servers was what actually fixed the problem, but restarting the servers again hasn't fixed the problem.

**Comment by Hussell** [comment]
When I execute dir("/sgm/trash") in R, sometimes I get the error, and others I get a list of the files in that directory. I don't understand why I'm getting different results each time.

**Comment by Hussell** [comment]
Ok, I think I've got it. The non-deterministic behaviour was a red herring. Receiver SG-3214BBBK8648 has a bunch of files with accented characters in the filenames ("Bahía de Asunción"), and the R dir() and list.files() functions are failing whenever they try to return these filenames. Moving them out of the trash fixed the problem for all other receivers, but this receiver still can't be rerun.

Perhaps write a function to replace non-ASCII characters in all filenames? (Ideally the bug in dir would be fixed, but this seems unlikely.)

**Comment by jbrzusto** [comment]
The R servers need to be running as user "sg".  Running them as "root" is dangerous and prone
to breaking things, e.g.  MotusDev/Motus-TO-DO#239 because the root environment won't have
the same PATH and other symbols defined.

**Comment by jbrzusto** [comment]
The translateCharUTF8 issue is a low-level bug somewhere in R.
e.g.:
```R
R --silent
> x = dir("/sgm/file_repo/SG-3214BBBK8648", recursive=TRUE, full.names=TRUE)
## significant pause, then an error:
Error in dir("/sgm/file_repo/SG-3214BBBK8648", recursive = TRUE, full.names = TRUE) : 
  'translateCharUTF8' must be called on a CHARSXP
```
but if an internal, implicit call to some kind of character conversion function is made first,
 then the error does not occur, and filenames are read correctly:
```R
R --silent
> rawToChar(as.raw(c(0xeb, 0xc9, 0xde)))
"\xeb\xc9\xde"
> x = dir("/sgm/file_repo/SG-3214BBBK8648", recursive=TRUE, full.names=TRUE)
> ## no error, and quick completion
```
Regardless, the `moveToTrash()` function which causes this problem uses `moveFilesUniquely()` which is ridiculously slow for large target directories, so I'm adding a jobID hierarchy under
`/sgm/trash`
