### ISSUE TITLE
Error in rsqlite_send_query(conn@ptr, statement): database is locked

### ISSUE THREAD

**Issue by Hussell** [jbrzusto/motusServer#400]
When a user uploads several files for the same receiver at the same time (e.g. Jan.7z, Feb.7z, etc.), all but one job will fail with this error. I can rerun the jobs manually, one at a time, and they go through, but there should be a way to handle this automatically.

Recent examples are the jobs for project 1 on May 9th.

**Comment by jbrzusto** [comment]
which is really just #341

**Comment by jbrzusto** [comment]
So I'm closing this in deference to #341

**Comment by Hussell** [comment]
Still happening, so probably a different issue. E.g. if two SGfindtags subjobs are running at the same time for the same receiver, then both will fail with the message:

Error in safeSys(bcmd, quote = FALSE): Error 2 from 'LD_LIBRARY_PATH=/usr/local/lib/boost_1.60 /sgm/bin/find_tags_motus --pulses_to_confirm=8 --frequency_slop=0.5 --min_dfreq=0 --max_dfreq=12 --pulse_slop=1.5 --burst_slop=4 --burst_slop_expansion=1 --use_events --max_skipped_bursts=20 --default_freq=166.376 --resume --bootnum=53 --src_sqlite /sgm_local//motus_meta_db.sqlite /sgm/recv/SG-7A27RPI34AE0.motus 2>&1 ':
 unable to step statement
 Sqlite error: database is locked

I've been handling these as they come up by waiting until the top jobs are complete, then using the retryJob script to rerun the jobs one-at-a-time, but that seems like a dangerously error-prone way to handle this (not to mention time-wasting).

**Comment by Hussell** [comment]
Recent example: jobs 538906 and 539102.
