### ISSUE TITLE
authentication error with SG API

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusServer#415]
Trying to access the SG logs now results in an authentication error, for all users as far as I can tell. This started either today or yesterday, I believe.

As far as I can try, these are resulting from any calls made to this API:
https://sgdata.motus.org/status2/authenticate_user

**Comment by denislepage** [comment]
Possibly a bit more useful details:

JSON response: "{\"error\":\"authentication failed: Error in readBin(\\\"\/dev\/urandom\\\", raw(), n = ceiling(MOTUS_TOKEN_BITS\/8)): object 'MOTUS_TOKEN_BITS' not found\\n\"}"

**Comment by jbrzusto** [comment]
closed by c13ba3f26eee9df115005e4335b99d39c257b9d0
